version: "2.3"
services:
  auth:
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    container_name: commo_auth
    ports:
      - 17845:17845
    depends_on:
      mysql:
        condition: service_healthy

  catalog:
    build: 
      context: ./catalog
      dockerfile: ./Dockerfile
    container_name: commo_catalog
    ports: 
      - 3000:3000

  mysql:
    image: mysql:latest 
    container_name: commo_mysql
    command: mysqld --user=root
    volumes:
      - main_mysql:/var/lib/mysql
      - ./initial_up.sql:/docker-entrypoint-initdb.d/initial_up.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=commo_db
      - MYSQL_USER=commo
      - MYSQL_PASSWORD=commo
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-psecret' ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  main_mysql: